# Basic dependabot.yml file with minimum configuration for two package managers

# You must store this file in the '.github' directory of your repository. When you add or update
# the dependabot.yml file, this triggers an immediate check for version updates. Any options that
# also affect security updates are used the next time a security alert triggers a pull request
# for a security update

# Supported schedule intervals
# -------------------------------
# * daily—runs on every weekday, Monday to Friday.
# * weekly—runs once each week. By default, this is on Monday. To modify this, use schedule.day.
# * monthly—runs once each month. This is on the first day of the month.
#
# Rebase Strategy
# ------------------
# See https://stackoverflow.com/a/68414395/4292075
# * auto to use the default behavior and rebase open pull requests when changes are detected.
# * disabled to disable automatic rebasing.
#
# Dependabot Access to Secrets
# -------------------------------
# https://github.com/dependabot/dependabot-core/issues/3253
# For GitHub Actions workflows initiated by Dependabot (github.actor == "dependabot[bot]") using the pull_request,
# pull_request_review, pull_request_review_comment, and push events: your GITHUB_TOKEN is read-only + secrets are inaccessible
#
# Grouping Dependabot version updates into one pull request
# -------------------------------------------------------------
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#grouping-dependabot-version-updates-into-one-pull-request
# By default, Dependabot raises a single pull request for each dependency that needs to be updated to a newer version.
# You can use groups to create sets of dependencies (per package manager), so that Dependabot opens a single PR
# to update multiple dependencies at the same time.
# The name of the group will become part of the PR title, e.g. if your group is named "everything"
#  the PR will result to "Bump the group 'everything' with 2 updates"
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"     # Disable rebasing for GH actions
    assignees: ["tillkuhn"]
    # for TF, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: ["*"]
        update-types: ["major","minor","patch"]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Enable version updates for npm (which also covers yarn)
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/angular"
    rebase-strategy: "disabled"     # Disable rebasing for npm ecosystem
    assignees: ["tillkuhn"]
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    # any packages matching the pattern @angular* where the highest resolvable version is minor or patch will be
    # grouped together. Dependabot will create a separate pull request for any package that doesn't match the pattern,
    # or that doesn't update to a minor or patch version.
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#example-3
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
    # configure dependency update ignores
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
    # supported update-types: version-update:semver-major, version-update:semver-minor, version-update:semver-patch
    # for versions use the standard pattern for the package manager. For example, for npm, use ^1.0.0 ( *MINOR and PATCH* will be updated to all future versions, but not MAJOR)
    ignore:
      # restrict angular updates, keep in sync with https://github.com/angular/angular/blob/15.2.x/package.json
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
      - dependency-name: "@angular*"
        update-types: [ "version-update:semver-major" ]

  # Enable version updates for Kotlin + Java libs
  - package-ecosystem: "gradle"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/kotlin"
    rebase-strategy: "disabled"  # Disable rebasing for gradle ecosystem
    assignees: ["tillkuhn"]
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      # restrict angular updates for the time being for some libs that require major changes
      - dependency-name: "com.tngtech.archunit:archunit*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.icegreen:greenmail"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
      # todo jackson


  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/imagine"
    rebase-strategy: "disabled"  # Disable rebasing for go eco-system
    assignees: ["tillkuhn"]
    # for GO, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: [ "*" ]
        update-types: [ "minor","patch" ]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/healthbells"
    rebase-strategy: "disabled"  # Disable rebasing for go eco-system
    assignees: ["tillkuhn"]
    # for GO, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: [ "*" ]
        update-types: [ "minor","patch" ]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/remindabot"
    rebase-strategy: "disabled"  # Disable rebasing for go eco-system
    assignees: ["tillkuhn"]
    # for GO, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: [ "*" ]
        update-types: [ "minor","patch" ]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/polly"
    rebase-strategy: "disabled"  # Disable rebasing for go eco-system
    assignees: ["tillkuhn"]
    # for GO, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: [ "*" ]
        update-types: [ "minor","patch" ]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/topkapi"
    rebase-strategy: "disabled"  # Disable rebasing for go eco-system
    assignees: ["tillkuhn"]
    groups:
      everything:
        patterns: [ "*" ]
        update-types: [ "minor","patch" ]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  # hcl 2.0 support? https://github.com/dependabot/dependabot-core/issues/1176
  - package-ecosystem: "terraform"
    directory: "/terraform"
    rebase-strategy: "disabled"  # Disable rebasing for terraform eco-system
    assignees: ["tillkuhn"]
    # for TF, try to group all minor and patch updates into a single PR
    groups:
      everything:
        patterns: ["*"]
        update-types: ["minor","patch"]
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Watch Dockerfile
  # In order for Dependabot to fetch Docker metadata, maintainers of Docker images must add the
  # org.opencontainers.image.source label to their Dockerfile, and include the URL of the source repository.
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
  - package-ecosystem: docker
    directory: /
    assignees: [ "tillkuhn" ]
    rebase-strategy: disabled  # Disable rebasing for GH actions
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
