# Basic dependabot.yml file with minimum configuration for two package managers

#  You must store this file in the .github directory of your repository. When you add or update
# the dependabot.yml file, this triggers an immediate check for version updates. Any options that
#  also affect security updates are used the next time a security alert triggers a pull request
#  for a security update

# Supported schedule intervals
# * daily—runs on every weekday, Monday to Friday.
# * weekly—runs once each week. By default, this is on Monday. To modify this, use schedule.day.
# * monthly—runs once each month. This is on the first day of the month.

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      
  # Enable version updates for npm (which also covers yarn)
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/angular"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
  
  # Enable version updates for Kotlin + Java libs
  - package-ecosystem: "gradle"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/kotlin"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/imagine"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/healthbells"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/remindabot"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/polly"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/go/topkapi"
    schedule:
      interval: "monthly"

  # Maintain dependencies for GitHub Actions
  # hcl 2.0 support? https://github.com/dependabot/dependabot-core/issues/1176
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
