# https://docs.antora.org/antora/2.2/playbook/playbook-schema/
site:
  ## title will appear prominently in the top right corner
  title: Angkor DevDocs
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.gitlab.io/demo/docs-site
  #start_page: component-b::doc.adoc
  ## first part must correspond with the name in antora.yml
  start_page: angkor-docs::index.adoc
content:
  sources:
    #- url: https://gitlab.com/antora/demo/demo-component-a.git
    #  branches: master
      # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
      # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    #  edit_url: false
    - url: .
      branches: master
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

output:
  dir: ./docs/build

asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
