# Antora - The Static Site Generator for Tech Writers
# https://docs.antora.org/antora/latest/instll-and-run-quickstart/
# https://docs.antora.org/antora/latest/playbook/
# cd to project root
# npm i -g @antora/cli@3.1 @antora/site-generator@3.1 @antora/lunr-extension
#
# antora --version
# @antora/cli: 3.1.5
# @antora/site-generator: 3.1.
#
site:
  # title will appear prominently in the top right corner
  title: Angkor DevDocs
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.gitlab.io/demo/docs-site
  ## first (component) part of start_page must correspond with the name in antora/antora.yml
  start_page: angkor-docs::index.adoc

content:
  sources:
    - url: .
      branches: main
      start_path: docs # local directory
   # - url: https://gitlab.com/antora/demo/demo-component-a.git
      # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
      # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    #  edit_url: false
 
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # supplemental_files: ./docs/supplemental-ui # no longer needed with antora3 

output:
  dir: ./docs/build

asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ''
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: '@antora/lunr-extension'
      snippet_length: 80
      index_latest_only: true
