spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  datasource:
    # set env SPRING_DATASOURCE_URL= jdbc:postgres://host:5432/dbname, same with USERNAME and PASSWORD
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      # ElefantSQL only supports 5 concurrent connections
      maximum-pool-size: 3 # SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "2"
      minimum-idle: 2 # SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  jpa:
    generate-ddl: false # we rely on flyway
    hibernate:
      ddl-auto: none # none, validate, update, create-drop.
    database: postgresql

---
spring:
  profiles: mock
  datasource:
    url: jdbc:h2:mem:db;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password:

---
spring:
  profiles: dev

---
spring:
  profiles: prod
