spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
---
spring:
  profiles: mock
  datasource:
    url: jdbc:h2:mem:db;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password:

---
spring:
  profiles: dev
  datasource:
    # set env SPRING_DATASOURCE_URL= jdbc:postgres://host:5432/dbname, same with USERNAME and PASSWORD
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none # none, validate, update, create-drop.
    database: postgresql
