package org.timafe.p2b

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import javax.persistence.Access
import javax.persistence.AccessType
import javax.persistence.Entity

@Entity
@DynamoDBTable(tableName = "Place")
data class Place (

        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String?,

        @DynamoDBAttribute
        var name: String

   )
