spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  datasource:
    # set env SPRING_DATASOURCE_URL= jdbc:postgres://host:5432/dbname, same with USERNAME and PASSWORD
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      # ElefantSQL only supports 5 concurrent connections
      maximum-pool-size: 3 # SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "2"
      minimum-idle: 2 # SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  jpa:
    generate-ddl: false # we rely on flyway
    hibernate:
      ddl-auto: none # none, validate, update, create-drop.
    database: postgresql
  jackson:
    serialization:
      INDENT_OUTPUT: true #stopped working with spring 2.3.1
logging:
  level:
    ROOT: INFO
    net.timafe.angkor: DEBUG
    ## X509Certificate: Alg:SHA256withRSA, (when interacting with cognito)
    jdk.event.security: INFO
    ## Your profile name includes a 'profile ' prefix.  blabla
    com.amazonaws.auth.profile.internal.BasicProfileConfigLoader: ERROR
    com.amazonaws.auth.AWS4Signer: INFO
    com.amazonaws.requestId: INFO

---
## see also config/application.properties in root folder
spring:
  profiles: default # we also use for dev

---
spring:
  profiles: prod
  flyway:
    clean-disabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: false # optimize for prod
---
spring:
  profiles: test

---
# deprecated, h2 does not work very well with postgres specific
# spring:
  # profiles: mock #
  # datasource:
    # https://www.baeldung.com/spring-testing-separate-data-source
    # https://medium.com/@jonashavers/how-to-create-database-test-data-for-spring-boot-applications-with-flyway-db-294a436db7ee
    #url: jdbc:h2:mem:db;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:angkor-db;MODE=PostgreSQL
    #username: sa
    #password: sa
    #driver-class-name: org.h2.Driver
    # spring.flyway.locations=classpath:/db/migration,classpath:/db/testdata


