# General properties, may be overwritten by specific profile or via Environment
# or via config/application.properties in root folder (not versioned)

# see config.AppProperties
app:
  upload-dir: /tmp/upload
  api-token: sieam-reap # only for local testing

logging:
  level:
    ROOT: INFO
    net.timafe.angkor: DEBUG
    ## X509Certificate: Alg:SHA256withRSA, (when interacting with cognito)
    jdk.event.security: INFO

# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics
  endpoint:
    # https://www.callicoder.com/spring-boot-actuator/#displaying-detailed-health-information
    health:
      show-details: always

server:
  forward-headers-strategy: native # avoid redirect issues with OAuth2 redirectUriTemplate https urls
  # https://stackoverflow.com/questions/44491257/how-to-reduce-spring-boot-memory-usage
  tomcat:
    threads:
      max: 20
  servlet:
    session:
      timeout: 12h # http session timeout default is 30 min
  error:
    # enable for nonprod: Starting from the 2.3 version, Spring Boot doesn't include an error
    # message on the default error page. The reason is to reduce the risk of leaking information to a client
    include-message: always

spring:
  datasource:
    # set env SPRING_DATASOURCE_URL= jdbc:postgres://host:5432/dbname, same with USERNAME and PASSWORD
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      # ElefantSQL only supports 5 concurrent connections, so we use small pool sizes
      maximum-pool-size: 3 # SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "2"
      minimum-idle: 2 # SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  jpa:
    generate-ddl: false # we rely on flyway
    hibernate:
      ddl-auto: none # none, validate, update, create-drop.
    database: postgresql
    open-in-view: false # to disable database queries may be performed during view rendering warning
  # list https://codingnconcepts.com/spring-boot/jackson-json-request-response-mapping
  jackson:
    serialization:
      indent-output: true #stopped working with spring 2.3.1 https://github.com/spring-projects/spring-boot/issues/20211
  #  date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  security:
    oauth2:
      client:
        registration:
          cognito:
            #  client-id: please_overwrite_via_env
            #  client-name: please_overwrite_via_env
            #  client-secret: please_overwrite_via_env
            scope: openid
            provider: cognito
            redirectUriTemplate: http://localhost:8080/login/oauth2/code/cognito
        provider:
          cognito:
            usernameAttribute: cognito:username
          # issuer-uri: please_overwrite_via_env
          # redirectUriTemplate: http://localhost:8080/login/oauth2/code/cognito # needed?
  servlet:
    multipart:
      max-file-size: 10MB # 1MB is default
      max-request-size: 10MB # 10MB is default
  mvc:
    converters:
      preferred-json-mapper: jackson

---
spring:
  profiles: default # we also use for dev
  datasource:
    url: jdbc:postgresql://localhost:5432/angkor_dev
    username: angkor_dev
    password:
   # spring.flyway.locations=classpath:/db/migration,classpath:/db/testdata

---
spring:
  profiles: prod
  flyway:
    clean-disabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: false # optimize for prod
server:
  error:
    include-message: never # disable for prod to avoid leaking of info to client (default for spring >= 2.3)

---
spring:
  profiles: test
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: dummy-for-testing
            client-name: dummy-for-testing
            client-secret: dummy-for-testing
        provider:
          cognito:
            issuer-uri: dummy-for-testing
---

