= Angular Frontend
:url-preferred-bootswatch-theme: https://bootswatch.com/sandstone/
:toc:

== Yarn npm ng cheatsheet

[source]
----
$ ng g c [some/path/]home # generate new component in src/app/some/path (some path is optional)
ng generate @angular/material:material-nav --name=nav # gen based on starter component
----

== Tollbar, Navigation Bar, Sidenav

.Tutorials in order of relevance to this project

* https://robferguson.org/blog/2018/11/10/angular-material-toolbar-and-sidenav/[Robs Angular Material: toolbar and sidenav lppls good]
    ** https://material.angular.io/guide/schematics#navigation-schematic[Angular Starter Components]
    ** https://robferguson.org/blog/2018/11/05/getting-started-with-angular-material/[Getting Started with Angular Material]
    ** https://serendipity-f7626.firebaseapp.com/[hosted app]
    ** https://github.com/Robinyo/serendipity[github serendipity]

* https://keepgrowing.in/angular/how-to-build-a-custom-collapsible-sidebar-navigation-with-angular-6/[How to build a custom collapsible sidebar navigation with Angular 6] and https://github.com/little-pinecone/angular-multi-layout-scaffolding[github] also nice and a bit more compact compared with robs tutorial
* https://code-maze.com/angular-material-navigation/[ngular Material Navigation Menu – Complete Responsive Navigation] with https://github.com/CodeMazeBlog/angular-material-series/tree/navigation[source on githb]
* https://auth0.com/blog/creating-beautiful-apps-with-angular-material/[Auth0 blog Creating Beautiful Apps with Angular Material]

----
ng generate @angular/material:material-nav --name=nav
ng generate service nav/nav
----

== File Upload

https://bezkoder.com/angular-spring-boot-file-upload/[Angular 8 + Spring Boot: File upload example]

== Configuraton Hacks via environment and post-build

* https://medium.com/@fidelisclayton/system-environment-variables-in-angular-1f4a922c7b4c[System environment variables in Angular with webpack - 2018]
* https://netbasal.com/customize-webpack-configuration-in-your-angular-application-d09683f6bd22[Customize Webpack Configuration in Your Angular Application - 2019]
* https://medium.com/angular-in-depth/handling-angular-environments-in-continuous-delivery-eeaee96f0aae[Handling Angular environments in continuous delivery nice read to support multiple configs]

.ConfigurationService load config via rest
----
import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {Observable} from 'rxjs';
import {shareReplay} from 'rxjs/operators';

interface Configuration {
  resourceServerA: string;
  resourceServerB: string;
  stage: string;
}

@Injectable({providedIn: 'root'})
export class ConfigurationService {

  private readonly BACKEND_URL = 'http://localhost:3000';
  private configuration$: Observable<Configuration>;

  constructor(private http: HttpClient) {
  }

  public loadConfigurations(): any {
    if (!this.configuration$) {
      this.configuration$ = this.http.get<Configuration>(`${this.BACKEND_URL}/configuration`).pipe(
        shareReplay(1)
      );
    }
    return this.configuration$;
  }

}
----

== Global Loading Spinner / Progress Bar

.before app is bootstrapped
Tons of tutorials here, let's try https://christianlydemann.com/four-ways-to-create-loading-spinners-in-an-angular-app/[The Four ways to Create Loading Spinners in an Angular App]
first which looks most promising

.during app on each xhr
https://stackoverflow.com/questions/50100380/how-to-show-spinner-for-every-http-requests-in-angular-5[How to Show spinner for every HTTP requests in angular 5?]

.during app on each xhr II
https://stackoverflow.com/questions/49385369/angular-show-spinner-for-every-http-request-with-very-less-code-changes[Angular show spinner for every HTTP request with very less code changes]
which improves https://grensesnittet.computas.com/loading-status-in-angular-done-right/[Loading-status in Angular done right]
mind https://github.com/angular/angular/issues/17572#issuecomment-486872994[ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked] fix

TIP: Use https://github.com/typicode/json-server#cli-usage[json-server]'s `--delay` switch to mock artificial Rest response delays for testing spinners.

== Toast Service / SnackBar

https://www.npmjs.com/package/ngx-toastr[ngx-toastr] with https://blog.jscrambler.com/how-to-create-angular-toastr-notifications/[How to Create Angular Toastr Notifications] looks nice,
but for the time being we stick with https://material.angular.io/components/snack-bar/overview[angular material snackbar]
which chips out-of-the-box with Angular Material and is also very well documented.

== Chips Example

* https://material.angular.io/components/chips/examples[chips autocomplete] also on https://stackblitz.com/angular/nvvprnjkmvmp?file=src%2Fapp%2Fchips-autocomplete-example.ts[stackblitz]
* https://stackoverflow.com/questions/52061184/input-material-chips-init-form-array[Input Material Chips — Init Form Array on Stackoverflow]

== mat-icon, SVG Icons, Free icons

* https://www.digitalocean.com/community/tutorials/angular-custom-svg-icons-angular-material[Support svg as angualar icon]
* https://material.angular.io/components/icon/overview#svg-icons[official angular doc how to include svg DomSanitizer]
* https://material.io/resources/icons/?style=baseline[the hard-to-find mat icon overview]

== Mapbox GL support

[quote,https://docs.mapbox.com/mapbox-gl-js/api/]
Mapbox GL JS is a JavaScript library that uses WebGL to render interactive maps from vector tiles and Mapbox styles. It is part of the Mapbox GL ecosystem

* https://docs.mapbox.com/help/how-mapbox-works/access-tokens/[access token handling, consider using rotation api]
Angular binding of mapbox-gl-js https://github.com/Wykks/ngx-mapbox-gl[ngx-mapbox-gl]

* Installation
[source,shell script]
----
// Install
yarn add ngx-mapbox-gl mapbox-gl
yarn add  @types/mapbox-gl --dev  ## mapbox-gl types for development

// styles.scss
@import '~mapbox-gl/dist/mapbox-gl.css';
@import '~@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css';

// polyfill.ts
(window as any).global = window;
----

== CSS flag country icons as background and span tag

* https://github.com/lipis/flag-icon-css[flag-icon-css github], https://docs.angularactivity.com/angular-7-flag-icon-css[article], https://flagicons.lipis.dev/[demo]
* https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css[or just us CDN version to avoid creating thousands of svg files]

Note: you can add styles in `styles.scss` AND `angular.json` !!
[source,html]
----
<td class="flag-icon-background flag-icon-{{row.country}}" ></td>
<span class="flag-icon flag-icon-{{row.country}} flag-icon-squared" ></span>
----

== Proxying frontend to backend

=== locally with webpack dev server

We use the proxying support in the webpack dev server to divert `/api` and certain other URLs to a backend server,
by passing a file to the `--proxy-config build` option.
See https://angular.io/guide/build#proxying-to-a-backend-server[Proxying to a backend server]

1. define all backend pathes to be proxied to localhost:8080 in new file `src/proxy.conf.js`
1. Add `"proxyConfig": "src/proxy.conf.js"` to `architect.serve.builder.options` in `angular.json`
1. `apiUrlRoot` in `src/environments/environment.ts` now no longer needs the hostname, similar to prod setup

----
$ ng serve
[HPM] Proxy created: [ '/api', '/auth', '/oauth2', '/login', '/actuator' ]  ->  http://localhost:8080
----

=== in prod with nginx reverse proxy

See `nginx.conf`

== Angular Testing (Karma)

* https://www.hhutzler.de/blog/angular-6-using-karma-testing/#Error_Datails_NullInjectorError_No_provider_for_Router[Quickfixes for Karma Setup / common errors]
* https://indepth.dev/angular-testing-with-headless-chrome/[https://indepth.dev/angular-testing-with-headless-chrome/]


== Themes beyond prebuild

Right now were using Angular material prebuild themes, but would be cool to evaluate
https://www.npmjs.com/package/bootswatch[bootswatch] in combination with https://ng-bootstrap.github.io/[ng-bootstrap],
espcially {url-preferred-bootswatch-theme}[this theme]  looks nice

== Integrate with NGINX (separate doc?)

* https://github.com/kubernetes/examples/blob/master/staging/https-nginx/auto-reload-nginx.sh[nginx auto reload config script]


== More resources
* Check https://github.com/aveferrum/angular-material-demo[Angular Material Demo Application with up-to-date dependencies]
* https://www.djamware.com/post/5d0eda6f80aca754f7a9d1f5/angular-8-tutorial-learn-to-build-angular-8-crud-web-app[Angular 8 Tutorial: Learn to Build Angular 8 CRUD Web App products]
* https://cycle.js.org/basic-examples.html#basic-examples-increment-a-counter-what-is-the-convention[What is the $ convention?]
"`The dollar sign $ suffixed to a name is a soft convention to indicate that the variable is a stream. It is a naming helper to indicate types.`"


