= Build + CI/CD
:toc:

== IntelliJ

=== JDK 14
Remove "Enable Launch Optimization" to supress following warning
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

=== Gradle Version Issues
**IntelliJ IDEA -> Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle**

use specified location e.g. `/usr/local/Cellar/gradle/6.2.2/libexec`

use same Gradle JVM e.g. 11.0.7 as in
Project Structure -> Platform Settings -> SDKs e.g. /Users/myname/.sdkman/candidates/java/11.0.7-zulu/zulu-11.jdk/Contents/Home (recommended use of https://sdkman.io/[sdkman])
which should resolve to the same JDK as your shell's `$JAVA_HOME` var

sdk list gradle https://stackoverflow.com/questions/28928106/install-upgrade-gradle-on-mac-os-x[Install / upgrade gradle on Mac OS X]
sdk install gradle 6.5


== CLI

Self documented based on Self documented based on https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html[Self-Documented Makefile]
https://www.gnu.org/software/make/manual/make.html[GNU Make]

[source,shell script]
----
$ make
tfinit                         runs terraform init
tfplan                         runs terraform plan with implicit init and fmt (alias: plan)
tfapply                        runs terraform apply with auto-approval (alias: apply)
ec2stop                        stops the ec2 instance (alias: stop)
ec2start                       launches the ec-2instamce (alias: start)
ec2status                      get ec2 instance status (alias: status)
ec2login                       ssh logs into current instance (alias: ssh)
ec2pull                        pulls recent config and changes on server side, triggers docker-compose up (alias: pull)

apiclean                       cleans up build/ folder in api
apibuild                       assembles backend jar with gradle (alias: assemble)
apirun                         runs springBoot app using gradle bootRun (alias: bootrun)
apideploy                      build api docker image and deploys to dockerhub

uiclean                        cleans up dist/ folder in ui
uibuild                        builds ui
uibuild-prod                   builds ui --prod
uirun                          runs ui with ng serve and opens browser (alias: serve)
uideploy                       build ui prod, creates docker image and deploys to dockerhub
uimock                         runs mockapi server for frontend
allclean                       Clean up build artifact directories in backend and frontend (alias: clean)
allbuild                       Builds frontend and backend (alias: build)
alldeploy                      builds and deploys frontend and backend images (alias deploy)
----

== CI/CD Integration

=== Github Actions

* https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags[perform action on tag push]
* https://medium.com/faun/continuous-integration-of-java-project-with-github-actions-7a8a0e8246ef[Continuous Integration of Java project with GitHub Actions]
* https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle[Github Building and testing Java with Gradle]
* https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e[Publishing to GitHub Packages with Gradle and GitHub Actions]
Cool Inspiration: https://github.com/smyrick/kotlin-extensions/tree/master/.github/workflows
* https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token[Authenticating with the GITHUB_TOKEN]
