= Build + CI/CD
:toc:

== IntelliJ

=== JDK 14
Remove "Enable Launch Optimization" to supress following warning
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

=== Gradle Version Issues
**IntelliJ IDEA -> Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle**

use specified location e.g. `/usr/local/Cellar/gradle/6.2.2/libexec`

use same Gradle JVM e.g. 11.0.7 as in
Project Structure -> Platform Settings -> SDKs e.g. /Users/myname/.sdkman/candidates/java/11.0.7-zulu/zulu-11.jdk/Contents/Home (recommended use of https://sdkman.io/[sdkman])
which should resolve to the same JDK as your shell's `$JAVA_HOME` var

sdk list gradle https://stackoverflow.com/questions/28928106/install-upgrade-gradle-on-mac-os-x[Install / upgrade gradle on Mac OS X]
sdk install gradle 6.5


== CLI

Self documented based on Self documented based on https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html[Self-Documented Makefile]
https://www.gnu.org/software/make/manual/make.html[GNU Make]

[source,shell script]
----
$ make
  api-clean            Cleans up ./api/build folder
  api-build            Assembles backend jar in ./api/build with gradle (alias: assemble)
  api-run              Runs springBoot API in ./api using gradle bootRun (alias: bootrun)
  api-dockerize        Builds API docker images on top of recent opdenjdk
  api-push             Build and tags API docker image, and pushes to dockerhub
  api-deploy           Deploys API with subsequent pull and restart of server on EC2

  ui-clean             Remove UI dist folder ./ui/dist
  ui-build             Run ng build  in ./ui
  ui-build-prod        Run ng build --prod in ./ui
  ui-run               Run UI with ng serve and opens UI in browser (alias: serve,open)
  ui-dockerize         Creates UI docker image based on nginx
  ui-push              Creates UI docker frontend image and deploys to dockerhub
  ui-deploy            Deploys UI with subsequent pull and restart of server on EC2
  ui-mocks             Run json-server on foreground to mock API services for UI (alias: mock)

  infra-init           Runs terraform init on working directory ./infra
  infra-plan           Runs terraform plan with implicit init and fmt (alias: plan)
  infra-deploy         Runs terraform apply with auto-approval (alias: apply)

  ec2-stop             Stops the ec2 instance (alias: stop)
  ec2-start            Launches the ec-2instamce (alias: start)
  ec2-status           Get ec2 instance status (alias: status)
  ec2-ps               Run docker compose status on instance (alias: ps)
  ec2-login            Exec ssh login into current instance (alias: ssh)
  ec2-pull             Pull recent config on server, triggers docker-compose up (alias: pull)

  docs-clean           Cleanup docs build directory
  docs-build           Generate documentation site using antora-playbook.yml (alias: docs)
  docs-push            Generate documentation site and push to s3
  docs-deploy          Deploys docs with subsequent pull and restart of server on EC2

  all-clean            Clean up build artifact directories in backend and frontend (alias: clean)
  all-build            Builds frontend and backend (alias: build)
  all-deploy           builds and deploys frontend and backend images (alias deploy)

  angkor               The ultimate target - builds and deploys everything 🦄----

== CI/CD Integration

=== Github Actions

* https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags[perform action on tag push]
* https://medium.com/faun/continuous-integration-of-java-project-with-github-actions-7a8a0e8246ef[Continuous Integration of Java project with GitHub Actions]
* https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle[Github Building and testing Java with Gradle]
* https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e[Publishing to GitHub Packages with Gradle and GitHub Actions]
Cool Inspiration: https://github.com/smyrick/kotlin-extensions/tree/master/.github/workflows
* https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token[Authenticating with the GITHUB_TOKEN]

=== Post Action Webhook

==== https://github.com/marketplace/actions/workflow-webhook-action[Workflow Webhook Action]
A Github workflow action to call (POST) a remote webhook endpoint with a json payload

[source,yaml]
----
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{ "module": "api", "drink" : "milk" }'
----
Tip: The hash signature is identical to that which a regular Github webhook would generate, and sent in a header field named `X-Hub-Signature`.


* https://stackoverflow.com/questions/28228392/failed-to-verify-github-x-hub-signature-in-my-application[ verify GitHub X-Hub-Signature in my application]
