= DevOps
:toc:

== Keeping Things up2date

=== UI (Frontend)

Use https://angular.io/cli/update[ng update] to update  application and its dependencies.
Following order is recommened ("don't update to much at the same time")

[source,shell script]
----
# update yarn package manager, e.g. via brew
$ brew upgrade yarn
==> Upgrading yarn 1.22.5 -> 1.22.10
----
----
# check if everything is OK *before* you update dependencies
cd ui/
$ yarn test:headless

# check which anguluar components *can* be updated (safe operation)
$ ng update

We analyzed your package.json, there are some packages to update:

  Name                               Version                  Command to update
 --------------------------------------------------------------------------------
  @angular/cdk                       10.1.3 -> 10.2.1         ng update @angular/cdk
  @angular/cli                       10.0.6 -> 10.1.1         ng update @angular/cli
  @angular/core                      10.0.9 -> 10.1.1         ng update @angular/core
  @angular/material                  10.1.3 -> 10.2.1         ng update @angular/material
  rxjs                               6.6.2 -> 6.6.3           ng update rxjs

# update at leat CLI + Core, optionally also cdk, material and rxjs
$ ng update @angular/cli @angular/core @angular/cdk @angular/material rxjs

# run tests again to chec if everything is still working
$ yarn test:headless
TOTAL: 15 SUCCESS

# Use `--all` to update all packages in package.js, optionally with --allow-dirty
$ ng update --all --allow-dirty

----

=== Core/API (Backend)

==== Libraries
Use the very efficient https://github.com/ben-manes/gradle-versions-plugin[gradle-versions-plugin],
add  `id("com.github.ben-manes.versions") version "0.33.0"` to the `plugins` block of `build.gradle.kts `

----

$ ./gradlew dependencyUpdates

 - org.springframework.boot:spring-boot-starter-test [2.3.2.RELEASE -> 2.3.3.RELEASE]
     https://spring.io/projects/spring-boot
 (...)
Gradle release-candidate updates:
 - Gradle: [6.5 -> 6.6.1 -> 6.7-rc-1]

Generated report file build/dependencyUpdates/report.txt

----

==== Dockerfile

Check JRE / JDCK version in `api/Dockerfile` and compare with recent versions on https://hub.docker.com/r/adoptopenjdk/openjdk14[dockerhub ]

----
ARG FROM_TAG=jre-14.0.2_12-alpine
FROM adoptopenjdk/openjdk14:$FROM_TAG
----

=== Infra

==== Terraform
* Use `tfswitch -l` and check https://github.com/hashicorp/terraform/releases[ hashicorp/terraform releases] for new versions
* Update `infra/.terraform-version`
* run `make plan`
* Update terraform_version in `.github/workflows/infra.yml`

==== AWS EC2
* Check for new AMI
* ...


== On EC2 Instance (automized or to be automized)

=== System logs

https://www.linuxuprising.com/2019/10/how-to-clean-up-systemd-journal-logs.html[How To Clear The systemd journal Logs]

Check `/etc/systemd/journald.conf`
----
$ journalctl --disk-usage
Archived and active journals take up 64.0M on disk
# does not work?
$ sudo journalctl -m --vacuum-time=1m
$ journalctl -m --vacuum-size=20M
----
