= Security
:toc:

== Certbot in a Nutshell

From https://dzone.com/articles/spring-boot-secured-by-lets-encrypt[Spring Boot Secured By Let's Encrypt]
How to use the Let's Encrypt tool with Spring Boot to generate HTTPS certificates and automatically renew them.

By executing following command in your terminal, Let's Encrypt generates certificates and a private key for you.

```
$ ./certbot-auto certonly -a standalone -d seeld.eu -d www.seeld.eu
```
Keys are generated in `/etc/letsencrypt/live/seeld.eu`.
Remark: 'certonly' - means that this command does not come with any special plugin like Apache or Nginx. 'standalone' -  means that Let's encrypt will automatically create a simple web server on port 80 to prove you control the domain.


* Use https://certbot.eff.org/docs/using.html#standalone[standalone mode]

show certbot exchange log

[source]
----
certbot --standalone -m ${certbot_mail} --agree-tos --redirect -n -d ${certbot_domain_name} certonly
tail /var/log/letsencrypt/letsencrypt.log

## rerun of entire command is safe it only shows
`Certificate not yet due for renewal; no action taken.`

## BUT NEW INSTANCE AFTER DESTROY STARTS WITH NEW FILESYSTEM, so we need to restore from s3
# to avoid "too many requests" issue
----

List cerbot certificates

[source]
----
$ certbot certificates
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name:  full.domain.name
    Serial Number: 4b58xxxxxxxxxxxxxxxxxxxx
    Domains: full.domain.name
    Expiry Date: 2020-09-13 13:50:55+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/full.domain.name/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/full.domain.name/privkey.pem
----


[source]
----
if [ -d /etc/letsencrypt/live ]; then
    echo "[INFO] Backup /etc/letsencrypt folder to s3://${bucket_name}"
    tar -C /etc -zcf /tmp/letsencrypt.tar.gz letsencrypt
    aws s3 cp --sse=AES256 /tmp/letsencrypt.tar.gz s3://${bucket_name}/backup/letsencrypt.tar.gz
fi
----

== Renewal Process
Let's Encrypt certificates are only valid for 90 days which should encourage automation
This command checks the expiry date of certificates located in this machine (managed by Let's Encrypt), and renew the ones that are either expired or about to expire.

```
    # add me https://serverfault.com/questions/790772/cron-job-for-lets-encrypt-renewal
    ## CRON
    ## sudo certbot renew --post-hook "systemctl reload nginx"
```
