= Security
:toc:

== Enable OAuth2

=== AWS Cognito Setup

==== Cognito → User Pool xxx → General Settings → App Clients

|===
|Attribute |  Purpose

|Name,
|spring.security.oauth2.client.registration.cognito.client-name

|App client id
|spring.security.oauth2.client.registration.cognito.client-id

|App client secret
|spring.security.oauth2.client.registration.cognito.client-secret
|===

Enable "refresh token based authentication (ALLOW_REFRESH_TOKEN_AUTH)"

==== Cognito → User Pools xxx → App Integration
===== App Client Settings

* Enabled Identity Providers *Facebook + Cognito User Pool*
* Allowed OAuth Flows: At least *Authorization code grant*
Comma separated List of Callback URL(s), e.g.
`http://localhost:8080/login/oauth2/code/cognito,http://localhost:4200/login/oauth2/code/cognito ...

===== Domain Name:
Use Prefix  **XXX** .auth.eu-central-1.amazoncognito.com

==== Cognito → User Pools xxx → Federation → Identity Providers → Facebook

* Facebook app ID and App secret: Taken From https://developers.facebook.com/apps/
* Authorize Scope: *public_profile,email*

==== Facebook Developers → App XXX → Products → Facebook Login → Settings

* Enable *Client Auth Login*, *Web Oauth login*, *Https*
* Add App Domains: xxxx.auth.eu-central-1.amazoncognito.com (from Amazon Cognito domain)
* Add Platform -> Webpage -> https://xxxx.auth.eu-central-1.amazoncognito.com/oauth2/idpresponse
* Setup Valid Oauth redirect Url: https://xxxxx.auth.eu-central-1.amazoncognito.com/oauth2/idpresponse
* For more details refer to https://developers.facebook.com/docs/facebook-login/[Setup Facebook Login]

=== Selected Tutorials
* https://www.baeldung.com/spring-security-oauth-cognito[Authenticating with Amazon Cognito Using Spring Security]
* https://stackoverflow.com/questions/48327369/amazon-cognito-oauth2-with-spring-security[A great starting point for Oauth2 using the latest Sprint Boot 2.x / Sprint Security 5.x can be found] here ...
* https://medium.com/@arjunsk/resource-server-with-cognito-b7fbfbee0155[Integrate Spring Boot Resource Server with Cognito Identity Provider]
* https://www.baeldung.com/spring-security-oauth-cognito[Baeldung Authenticating with Amazon Cognito Using Spring Security]

. build.gradle.kts
----
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
----

=== Issues

* https://stackoverflow.com/questions/59126518/how-to-cope-with-x-forwarded-headers-in-spring-boot-2-2-0-spring-web-mvc-behin[How to cope with x-forwarded-headers in Spring Boot 2.2.0? (Spring Web MVC behind reverse proxy)]
* https://stackoverflow.com/questions/33812471/spring-oauth-redirect-uri-not-using-https[Spring OAuth redirect_uri not using https]

.Explanation
Even if `spring.security.oauth2.client.provider.cognito.issuer-uri` is an https url, it will resolved to http if spring
boot is running behind an ssl terminating proxy. To avoid redirect issues, as of spring boot 2.2. you should set
`server.forward-headers-strategy=NATIVE` (in previous versions: `server.use-forward-headers:`) and make sure your
nginx config sets the headers accordingly

----
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
----

== Certbot
=== Certbot in a Nutshell

Source: https://dzone.com/articles/spring-boot-secured-by-lets-encrypt[Spring Boot Secured By Let's Encrypt]
(How to use the Let's Encrypt tool with Spring Boot to generate HTTPS certificates and automatically renew them.)

By executing following command in your terminal, Let's Encrypt generates certificates and a private key for you.

```
$ ./certbot-auto certonly -a standalone -d seeld.eu -d www.seeld.eu
```
Keys are generated in `/etc/letsencrypt/live/seeld.eu`.
Remark: 'certonly' - means that this command does not come with any special plugin like Apache or Nginx. 'standalone' -  means that Let's encrypt will automatically create a simple web server on port 80 to prove you control the domain.


* Use https://certbot.eff.org/docs/using.html#standalone[standalone mode]

show certbot exchange log

[source]
----
certbot --standalone -m ${certbot_mail} --agree-tos --redirect -n -d ${certbot_domain_name} certonly
tail /var/log/letsencrypt/letsencrypt.log

## rerun of entire command is safe it only shows
`Certificate not yet due for renewal; no action taken.`

## BUT NEW INSTANCE AFTER DESTROY STARTS WITH NEW FILESYSTEM, so we need to restore from s3
# to avoid "too many requests" issue
----

List cerbot certificates

[source]
----
$ certbot certificates
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name:  full.domain.name
    Serial Number: 4b58xxxxxxxxxxxxxxxxxxxx
    Domains: full.domain.name
    Expiry Date: 2020-09-13 13:50:55+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/full.domain.name/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/full.domain.name/privkey.pem
----


[source]
----
if [ -d /etc/letsencrypt/live ]; then
    echo "[INFO] Backup /etc/letsencrypt folder to s3://${bucket_name}"
    tar -C /etc -zcf /tmp/letsencrypt.tar.gz letsencrypt
    aws s3 cp --sse=AES256 /tmp/letsencrypt.tar.gz s3://${bucket_name}/backup/letsencrypt.tar.gz
fi
----

=== Renewal Process
Let's Encrypt certificates are only valid for 90 days which should encourage automation
This command checks the expiry date of certificates located in this machine (managed by Let's Encrypt), and renew the ones that are either expired or about to expire.

```
# add me https://serverfault.com/questions/790772/cron-job-for-lets-encrypt-renewal
## CRON
## sudo certbot renew --post-hook "systemctl reload nginx"
```

=== More Certbot / Letsencrypt Web Resources

* https://www.freecodecamp.org/news/going-https-on-amazon-ec2-ubuntu-14-04-with-lets-encrypt-certbot-on-nginx-696770649e76/[Using the Let’s Encrypt Certbot to get HTTPS on your Amazon EC2 NGINX box]
* https://medium.com/@andrenakkurt/great-guide-thanks-for-putting-this-together-gifford-nowland-c3ce0ea2455[fix cerbot install issue on amazon linux 2]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html#letsencrypt[Official aws ertificate Automation: Let's Encrypt with Certbot on Amazon Linux 2]
* https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7[Generate Wildcard SSL certificate using Let’s Encrypt/Certbot]


