= HCP Vault Secrets

As of 2023-10, Project {app-name}  https://developer.hashicorp.com/hcp/docs/vault-secrets[HashiCorp Cloud Platform (HCP) Vault Secrets], which "is a secrets lifecycle management solution to centralize your secrets and enable applications to access them from their workflow. The clients (systems or users) can interact with HCP Vault Secrets using command-line interface (CLI), HCP Portal, or API."

== Install CLI

.https://developer.hashicorp.com/vault/tutorials/hcp-vault-secrets-get-started/hcp-vault-secrets-install-cli
----
curl -fsSL https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo | sudo tee /etc/yum.repos.d/hashicorp.repo
sudo yum update
sudo yum install vlt -y
----

.interact
----
export HCP_ORGANIZATION=79b(...)
vlt login
vlt apps --project 928afd2b-3dfb-47f5-800a-a383736349e8
Name       Description                       Created At
confluent  HCP Secrets Store for angkor App  2023-09-26T18:09:26.511Z
github     test github integration           2023-09-26T17:00:52.458Z

vlt secrets --app-name confluent
Name                              Latest Version  Created At
confluent_cluster_api_key_key     1               2023-09-26T18:09:26.856Z
confluent_cluster_api_key_secret  1               2023-09-26T18:09:27.040Z

$ vlt secrets get --app-name test -plaintext  hello
something
----

. vlt secrets only returns a list but not the actual secret. To iterate via CLI use the following approach (which is very slow)
----
for s in $(vlt secrets --app-name confluent -format json |jq -r '.[].name'); do
    echo -n "$s=" | tr a-z A-Z; vlt secrets get --app-name confluent --plaintext  $s;
done
----

.Hack to get all secrets with one CLI call. It's much faster and uses the run subcmd ("Run a process while injecting secrets as ENV vars") to print the environment. We use `env -i` to "Execute the utility with only those environment variables specified by name=value options", since we need at least PATH and HCP Vars for authentication, which we filter out subsequently using `grep -v`

----
env -i PATH="$PATH" HCP_ORGANIZATION=$HCP_ORGANIZATION HCP_CLIENT_ID=$HCP_CLIENT_ID  HCP_CLIENT_SECRET=$HCP_CLIENT_SECRET HCP_PROJECT=$HCP_PROJECT \
  vlt run --app-name runtime-secrets  printenv | \
  grep -ve "^HCP_" | grep -ve "^PATH"
DB_PASSWORD=******
OAUTH2_SECRET=******
----

== Troubleshooting

.TF Plugin is not super robust, especially if you remove apps. In case of crashes, delete via HCP WebUI and remove previous TF state afterwards.
----
terraform state list
terraform state rm module.confluent.hcp_vault_secrets_app.main (...)
----
