@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/nginx_original.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/angularjs.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/kotlin.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/go.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/postgresql.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/amazonwebservices_original.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/docker.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material/security.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2/github_original.puml
!include https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/cloudinsight/kafka.puml

AddElementTag("aws",$bgColor="#FF9900",$fontColor="FFFFFF")

' https://github.com/plantuml-stdlib/C4-PlantUML Starting point for c3
' https://github.com/tupadr3/plantuml-icon-font-sprites#icon-sets for icons
' https://github.com/plantuml/plantuml-stdlib/tree/master/cloudinsight more icons inc kafka?

' skinparam monochrome false
' skinparam shadowing false

Person(user, "Happy User")
Person(admin, "Serious Admin")

Boundary(awsclous,"AWS Cloud") {
System_Boundary(ec2,"AWS EC2 Instance t4g.micro") {

        System_Boundary(docker, "docker-compose") {
            Container(ui, "Angkor UI", "https,nginx","WebFrontend","angularjs")
            Container(api, "Angkor API", "https,springboot","RestAPI","kotlin")
            Container(imagine, "Imagine", "https,s3api","ImageProxy","go")
            Container(healthbells, "Healthbells","https","Monitoring", "go")
        }
        Container(polly, "Polly SQS", "sqsapi,systemd","EventHandler","go")
        Container(remindabot, "Remindabot", "https,cronjob","Mailer","go")
    }

    System_Boundary(awsservices, "AWS Cloud Services (Saas)") {
        ComponentQueue(s3data, "S3 Storage","s3-api","","amazonwebservices_original", $tags="aws")
        ComponentQueue(ses,"SES Mail","smtp","","amazonwebservices_original", $tags="aws")
        ComponentQueue(sqs,"SQS Events","sqs-api","","amazonwebservices_original", $tags="aws")
        ComponentQueue(paramstore,"SSM Params","ssm-api","","amazonwebservices_original", $tags="aws")
        ComponentQueue(cognito,"AWS Cognito","oidc,https","","amazonwebservices_original", $tags="aws")
    }

}

cloud "Internet" as internet #AliceBlue {
}

Boundary(3rdpartycloud,"3rd Party Cloud Services") {

    Person(developer, "Busy Developer")

    Boundary(dockerhub,"DockerHub") {
        System_Ext(dockerrepos,"Docker Repositories","api,ui,tools","docker")
    }

    Boundary(elephantsql,"ElephantSQL") {
         ContainerDb(proddb, "DB Schema\nProd","jdbc","","postgresql")
         ContainerDb(testdb, "DB Schema\nTest","jdbc","","postgresql")
    }
    Boundary(kafka,"Cloudkarafka") {
         ContainerDb(kafkacluster, "Kafka Topics","tcp","app,system,\naudit,imagine","kafka")
    }

    Boundary(github,"GitHub") {
         ComponentDb(code, "Sourcecode\nRepository","ssh,https","","github_original")
         Container(actions, "Github Actions","workflows","","github_original")
     }
 }

user ..right.> internet
admin ..left.> internet
polly  <.down. sqs: [sqs-api]
remindabot .down.> ses: [smtp]
api .down..>proddb: [jdbc]

healthbells .down.> api
healthbells .down.> imagine
healthbells .right.> ui
api .down. cognito: [oidc]
ui .down. api: https
ui .down.> imagine
imagine .down. s3data: [s3-api]
docker <.. dockerrepos: pull
internet .down..> ui: [https]

actions ..> dockerrepos: push
actions .right.> testdb: jdbc
actions .up.> sqs: [sns-api]
actions .up.> s3data: [s3-api]
actions .up.> paramstore: [ssm-api]

code .up.> actions: trigger
developer .up.> code : [ssh]
@enduml
