@startuml

skinparam monochrome false
skinparam shadowing false

actor User as user

cloud "AWS Cloud" #AliceBlue {
    frame "AWS EC2" as aws #white {
        frame "docker-runtime" as docker {
            component "Angkor UI\n<<nginx>>" as ui
            component "Angkor API\n<<springboot>>" as api
            component "Imagine\n<<golang>>" as imagine
            component "HealthBells\n<<golang>>" as healthbells
        }
        frame "systemd" {
        component "Polly SQS\n<<golang>>" as polly
        }
    }
    frame "AWS Global Services" #white {
        database "S3 Data Bucket" as s3data #orange {
        }

        queue   "SQS Events" as sqs #orange {
        }
        node  "AWS Cognito" as cognito #orange
    }

}

cloud "Internet" as internet #AliceBlue {
}

cloud "3rd Party Cloud Services" #AliceBlue {

      actor Developer as developer
     frame DockerHub as dockerhub #white {
            database repos #cyan [
             angkor-ui
            ----
             angkor-api
            ----
             angkor-tools
            ]
     }

     frame "ElephantSQL" #white {
         database "Test DB" as testdb #008bb9
         database "Prod DB" as proddb #008bb9
     }

     frame GitHub as github #white {
         storage "Code Repo" as code
         [Action Workflows] as actions
     }
 }

polly -right-> docker
polly  <-down- sqs
api --down--->proddb
api -right- healthbells
api -down-> cognito
ui -> api
ui -left-> imagine
user --right-> internet
imagine -down-> s3data
docker ..down.. dockerhub
internet -down--> ui
actions -right-> dockerhub
actions -up-> sqs
code -up-> actions
code <-right- developer
@enduml
