@startuml

skinparam monochrome false
skinparam shadowing false

actor "Happy User" as user
actor "Serious Admin" as admin

cloud "AWS Cloud" #AliceBlue {
    frame "AWS EC2 Instance" as ec2 #white {
        frame "docker-runtime" as docker {
            component "Angkor UI\n<<nginx>>" as ui
            component "Angkor API\n<<springboot>>" as api
            component "Imagine\n<<golang>>" as imagine
            component "HealthBells\n<<golang>>" as healthbells
        }
        frame "systemd" {
          control "Polly SQS\n<<golang>>" as polly
        }
    }
    frame "AWS Application Services" #white {
        stack s3data #orange [
            S3 Data Storage
            ---
            S3 Doc Artifacts
        ]

        queue sqs #orange [
        SQS Events
        ---
        SNS Topic
        ]
        node  "AWS Cognito\nUser Pool" as cognito #orange
    }

}

cloud "Internet" as internet #AliceBlue {
}

cloud "3rd Party Cloud Services" #AliceBlue {

     actor "Busy\nDeveloper" as developer
     frame DockerHub as dockerhub #white {
            database dockerrepos #cyan [
             angkor-ui

            ----
             angkor-api

            ----
             angkor-tools

            ]
     }

     frame "ElephantSQL" #white {

            database proddb #008bb9 [
             angkor-prod-db

            ----
             angkor-test-db

            ----
             angkor-dev-db

            ]
     }

     frame GitHub as github #white {
         storage "Sourcecode Repo" as code
         component "Github Actions\n(Workflows)" as actions
     }
 }

user --right-> internet
admin --left-> internet
polly -right-> docker
polly  <-down- sqs
api --down--->proddb
api -right- healthbells
api -down-> cognito
ui -> api
ui -left-> imagine
imagine -down-> s3data
docker <- dockerrepos
internet -down--> ui

actions -right-> dockerhub
actions -up-> sqs
actions -up-> s3data

code -up-> actions
code <-right- developer
    @enduml
