package org.timafe.p2b.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.timafe.p2b.Constants
import javax.persistence.Entity

@Entity
@DynamoDBTable(tableName = Constants.DYNAMODB_PREFIX + "place")
data class Place(

        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String?,

        @DynamoDBAttribute
        var name: String,

        @DynamoDBAttribute
        var desc: String?

        //@DynamoDBAttribute
        //var updated: LocalDateTime = LocalDateTime.now()
)

