= Spring Boot

== Slimmer Jar?
* https://www.baeldung.com/spring-boot-thin-jar[spring-boot-thin-jar]
* https://openliberty.io/blog/2018/06/29/optimizing-spring-boot-apps-for-docker.html[Optimizing Spring Boot apps for Docker]
 and https://openliberty.io/blog/2018/07/02/creating-dual-layer-docker-images-for-spring-boot-apps.html[Creating Dual Layer Docker images for Spring Boot apps
]

== Relaxed Binding rules (environment vs properties)

[quote, spring boot manual]
____
To convert a property name in the canonical-form to an environment variable name you can follow these rules:

* Replace dots (.) with underscores (_).
* Remove any dashes (-).
* Convert to uppercase.

https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html[source] For example, the configuration property spring.main.log-startup-info would be an environment variable named SPRING_MAIN_LOGSTARTUPINFO.
____

== Interesting Spring resources on the Web

* https://dzone.com/articles/spring-boot-secured-by-lets-encrypt[Let's encrypt with Spring Boot] (but we use it only with nginx)
* Lot's of inspiration for https://kotlinlang.org/docs/tutorials/spring-boot-restful.html[Creating a RESTful Web Service with Spring Boot] Source https://github.com/Kotlin/kotlin-examples/tree/master/tutorials/spring-boot-restful[Github]
* https://www.baeldung.com/spring-boot-angular-web[Spring Boot bootstrapping class and populate the database with a few User entities] could be interesting

* https://tuhrig.de/dynamodb-with-kotlin-and-spring-boot/[DynamoDB with Kotlin and Spring Boot (Part 1)] (but we dumped dynamodb java integration)

* https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html[Deploying Spring Boot Applications]

* https://spring.io/guides/tutorials/spring-security-and-angular-js/[Spring Security and Angular]
* https://blog.codecentric.de/en/2019/08/spring-boot-heroku-docker-jdk11/[Spring Boot on Heroku with Docker Multistage builds, JDK 11 & Maven 3.5.x]

== Web File Upload
Note used right now (delegated to imagine, but if we re-add it )

.Controller
[source,kotlin]
----
    @PostMapping(Constants.API_PATH_PLACES + "/{id}/${Constants.API_PATH_FILES}")
    fun uploadPlaceFile(@PathVariable id: String, @RequestParam("file") file: MultipartFile): ResponseEntity<String?>? {
        var message: String
        var status: HttpStatus
        try {
            val storeDir =
                Files.createDirectories(Paths.get("/${appProperties.uploadDir}/${Constants.API_PATH_PLACES}/$id"))
            val writtenBytes = Files.copy(
                file.inputStream,
                storeDir.resolve(file.originalFilename!!),
                StandardCopyOption.REPLACE_EXISTING
            )
            message = "Successfully uploaded $writtenBytes bytes to $storeDir/${file.originalFilename}"
            files.add(file.originalFilename)
            status = HttpStatus.OK
            log.info(message)
        } catch (e: Exception) {
            status = HttpStatus.EXPECTATION_FAILED // 417
            message = "Failed to upload!" + e.message
            log.error(message)
        }
        return ResponseEntity.status(status).body(message)
    }
----

.Test
[source,kotlin]
----
    @Test
    @Throws(Exception::class)
    @WithMockUser(username = "hase", roles = ["USER"])
    fun testFileUpload() {
        val firstFile = MockMultipartFile("file", "recipe.txt", "text/plain", "pasta".toByteArray())
        mockMvc.perform(
            MockMvcRequestBuilders.multipart("${Constants.API_LATEST}/${Constants.API_PATH_PLACES}/815/${Constants.API_PATH_FILES}")
                .file(firstFile)
                .param("some-random", "4")
        )
            .andExpect(MockMvcResultMatchers.status().`is`(200))
            .andExpect(MockMvcResultMatchers.content().string(containsString("Successfully")))
    }

----
