= Build + CI/CD
:toc:

== CI/CD Process based on Github Actions
=== In a Nutshell ....

[plantuml,"PlantUML Test",png]
----
@startuml
skinparam handwritten true

interface "Developer" as developer
component "Github Actions" as github
component "Docker Hub" as dockerhub
component "EC2 Instance" as ec2

developer -> github: commit
github -> dockerhub: push
github -> ec2: notify
dockerhub <-- ec2 : pull

note right of dockerhub
  decicated repos
  for api and ui
end note

note right of ec2
  docker-compose restarts
  service if image changes
end note
@enduml
----

=== Github Actions

'''
.Checklist
* [x] api Gradle Build with Docker Push
* [x] ui Angular Build with Docker Push
* [x] docs Antora build
* [x] docs Deploy to S3 Bucket
* [ ] for all modules: trigger redeploy on new build


IMPORTANT: There is a lot to do!

'''

* https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags[perform action on tag push]
* https://medium.com/faun/continuous-integration-of-java-project-with-github-actions-7a8a0e8246ef[Continuous Integration of Java project with GitHub Actions]
* https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle[Github Building and testing Java with Gradle]
* https://medium.com/@shanemyrick/publishing-to-github-packages-with-gradle-and-github-actions-4ad842634c4e[Publishing to GitHub Packages with Gradle and GitHub Actions]
Cool Inspiration: https://github.com/smyrick/kotlin-extensions/tree/master/.github/workflows
* https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token[Authenticating with the GITHUB_TOKEN]

== Post Action Webhook

https://github.com/marketplace/actions/workflow-webhook-action[Workflow Webhook Action]
A Github workflow action to call (POST) a remote webhook endpoint with a json payload

[source,yaml]
----
  - name: Invoke deployment hook
    uses: distributhor/workflow-webhook@v1
    env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "module": "api", "drink" : "milk" }'
----

Tip: The hash signature is identical to that which a regular Github webhook would generate, and sent in a header field named `X-Hub-Signature`.

* https://stackoverflow.com/questions/28228392/failed-to-verify-github-x-hub-signature-in-my-application[ verify GitHub X-Hub-Signature in my application]
* https://ogma-dev.github.io/posts/simple-flask-webhook/[Simple Flask Webhook]
* https://blog.bearer.sh/consume-webhooks-with-python/[How to Listen for Webhooks with Python]
* https://bits.mdminhazulhaque.io/python/run-flask-app-with-let's-encrypt-ssl-certificate.html[Run Flask App with Let's Encrypt SSL Certificate]

[source,python]
----
if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080, ssl_context=('/etc/letsencrypt/live/domain.io/fullchain.pem', '/etc/letsencrypt/live/domain.io/privkey.pem'))
----


== Angkor Development CLI

The entire project uses https://www.gnu.org/software/make/manual/make.html[GNU Make] on top level to manage the various ecosystems for our different modules.
The *Makefile* documents itself when `make` is called without arguments (inspired by https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html[Self-Documented Makefile])

.Output of all documented make targets
[source,shell script]
----
$ make
  api-clean            Cleans up ./api/build folder
  api-build            Assembles backend jar in ./api/build with gradle (alias: assemble)
  api-run              Runs springBoot API in ./api using gradle bootRun (alias: bootrun)
  api-deploy           Deploys API with subsequent pull and restart of server on EC2

  ui-clean             Remove UI dist folder ./ui/dist
  ui-build             Run ng build  in ./ui
  ui-build-prod        Run ng build --prod in ./ui
  ui-run               Run UI with ng serve and opens UI in browser (alias: serve,open)
  ui-deploy            Deploys UI with subsequent pull and restart of server on EC2
  ui-mocks             Run json-server on foreground to mock API services for UI (alias: mock)

  infra-init           Runs terraform init on working directory ./infra
  infra-plan           Runs terraform plan with implicit init and fmt (alias: plan)
  infra-deploy         Runs terraform apply with auto-approval (alias: apply)

  ec2-stop             Stops the ec2 instance (alias: stop)
  ec2-start            Launches the ec-2instamce (alias: start)
  ec2-status           Get ec2 instance status (alias: status)
  ec2-ps               Run docker compose status on instance (alias: ps)
  ec2-login            Exec ssh login into current instance (alias: ssh)
  ec2-pull             Pull recent config on server, triggers docker-compose up (alias: pull)

  docs-clean           Cleanup docs build directory
  docs-build           Generate documentation site using antora-playbook.yml (alias: docs)
  docs-push            Generate documentation site and push to s3
  docs-deploy          Deploys docs with subsequent pull and restart of server on EC2

  all-clean            Clean up build artifact directories in backend and frontend (alias: clean)
  all-build            Builds frontend and backend (alias: build)
  all-deploy           builds and deploys frontend and backend images (alias deploy)

  angkor               The ultimate target - builds and deploys everything 🦄----
----

