= Angular Frontend
:url-preferred-bootswatch-theme: https://bootswatch.com/sandstone/

== Dyanmic Config ??

https://medium.com/angular-in-depth/handling-angular-environments-in-continuous-delivery-eeaee96f0aae
ConfigurationService 
----

import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {Observable} from 'rxjs';
import {shareReplay} from 'rxjs/operators';

interface Configuration {
  resourceServerA: string;
  resourceServerB: string;
  stage: string;
}

@Injectable({providedIn: 'root'})
export class ConfigurationService {

  private readonly BACKEND_URL = 'http://localhost:3000';
  private configuration$: Observable<Configuration>;

  constructor(private http: HttpClient) {
  }

  public loadConfigurations(): any {
    if (!this.configuration$) {
      this.configuration$ = this.http.get<Configuration>(`${this.BACKEND_URL}/configuration`).pipe(
        shareReplay(1)
      );
    }
    return this.configuration$;
  }

}
----

== Angular Material

* Check https://github.com/aveferrum/angular-material-demo[Angular Material Demo Application with up-to-date dependencies]
* https://www.digitalocean.com/community/tutorials/angular-custom-svg-icons-angular-material[Support svg as angualar icon]

== Mapbox GL support

[quote,https://docs.mapbox.com/mapbox-gl-js/api/]
Mapbox GL JS is a JavaScript library that uses WebGL to render interactive maps from vector tiles and Mapbox styles. It is part of the Mapbox GL ecosystem

* https://docs.mapbox.com/help/how-mapbox-works/access-tokens/[access token handling, consider using rotation api]
Angular binding of mapbox-gl-js https://github.com/Wykks/ngx-mapbox-gl[ngx-mapbox-gl]

* Installation
[source,shell script]
----
// Install
yarn add ngx-mapbox-gl mapbox-gl
yarn add  @types/mapbox-gl --dev  ## mapbox-gl types for development

// styles.scss
@import '~mapbox-gl/dist/mapbox-gl.css';
@import '~@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css';

// polyfill.ts
(window as any).global = window;
----

== Flag icons

https://github.com/lipis/flag-icon-css[flag-icon-css github], https://docs.angularactivity.com/angular-7-flag-icon-css[article], https://flagicons.lipis.dev/[demo]

https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css[or just us cdn version]
[source]
----
// install
yarn add flag-icon-css

// styles.scss:
@import '~flag-icon-css/css/flag-icon.min.css';

// example, flag-icon-squared is optional -
xxx.component.html: <span class="flag-icon flag-icon-{{place.country}}" flag-icon-squared title="{{place.country}}"></span>
----

Note: you can add styles in `styles.scss` AND `angular.json` !!
== Toolnar and side navigation

https://robferguson.org/blog/2018/11/10/angular-material-toolbar-and-sidenav/[Angular Material: toolbar and sidenav lppls good]

== Themes

Right now were using Angular material prebuild themes, but would be cool to evaluate
https://www.npmjs.com/package/bootswatch[bootswatch] in combination with https://ng-bootstrap.github.io/[ng-bootstrap],
espcially {url-preferred-bootswatch-theme}[this theme]  looks nice
