= GEO Data Handling and Mapbox Integration

== Finding the correct RegEx expression for your map's URL:
https://help.parsehub.com/hc/en-us/articles/226061627-Scrape-latitude-and-longitude-data-from-a-Google-Maps-link[Scrape latitude and longitude data from a Google Maps link]

Google format is **LAT**itude followed by **LON**ngitude and Z (altitude? data grid? we don't know and don't need)
Examples:
```
@41.25907,13.4254605,15z  Sperlonga
@-0.9175391,9.2298915,7z Gabun Äquator
@1.3143394,103.7041653,11z Singapur
```

If the latitude and longitude in the URL is preceded by an "@" symbol, e.g. https://www.google.ca/maps/@43.6474528,-79.3799409,14.78z):

.RegEx for Google Notation
|===
|**Type** |**RegEx**
|Latitude
|`\@(-?[\d\.]*)`
|Longitude
|`\@[-?\d\.]*\,([-?\d\.]*)`
|===

== Enter GeoJSON
* Bangkok Latitude and longitude coordinates are: 13.736717, 100.523186.
* @13.7244416,100.3529157 Bangkok **(Lat, Lon)!!!**
* geojson coordinates = [100.523186, 13.736717]  **(Lon,Lat)!!!**

[quote,rfc7946 GeoJSON Point, https://tools.ietf.org/html/rfc7946#section-3.1.2,]
A position is an array of numbers.  There MUST be two or more
elements.  The first two elements are longitude and latitude, or
easting and northing, precisely in that order and using decimal
numbers.  Altitude or elevation MAY be included as an optional third
element.

[source,json]
----
"geometry": {
    "type": "Point",
    "coordinates": [7.0069, 51.1623]
}
----

== Launch Google Maps and perform a specific action
Source: https://developers.google.com/maps/documentation/urls/guide#forming-the-url[guide#forming-the-url]

```
https://www.google.com/maps/search/?api=1&query=1.3143394,103.7041653  (lands in Singapur)
```
