= Angkor Kotlin API Backend

====
This is the getting started readme for the *Angkor Kotlin Module* in the `/kotlin` sub-folder,
for general Information on the Project please refer to the readme in the Project root!
====

== Install JDK and Gradle

* Install JDK, we recommend using https://sdkman.io/install[sdkman].
As of this writing angkor uses Java 16.x (Zulu)!
+
----
$ curl -s "https://get.sdkman.io" | bash # careful!
$ sdk list java # make your choice
$ sdk install java 16.0.2-zulu

$ java --version
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7)

$ ls -l ${HOME}/.sdkman/candidates/java
drwxr-xr-x  15 me  staff  480 21 Apr 02:25 16.0.2-zulu
lrwxr-xr-x   1 me  staff   11  5 Jun 23:47 current -> 16.0.2-zulu
----
+
[CAUTION]
====
IntelliJ Users: Use the same JDK in File -> Project Structure -> Project Settings -> Project and Platform Setting
-> SDKs (the specific version, **not** the `current` symlink).
You need to drill into the *Contents/Home* folder e.g.  `~.sdkman/candidates/java/16.0.2-zulu/zulu-16.jdk/Contents/Home`
====

* Install Gradle (or use https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper]).
As of this wiring angkor uses Gradle 7.x! Note you can also manage gradle versions via *sdkman*
+
----
$ sdk list gradle
$ sdk install gradle 7.0.2
$ gradle --version
Gradle 7.0.2
$ ls -l ${HOME}/.sdkman/candidates/gradle
drwxr-xr-x  8 me  staff  256  1 Feb  1980 7.0.2
lrwxr-xr-x  1 me  staff    5  5 Jun 23:54 current -> 7.0.2
----
+
[CAUTION]
====
IntelliJ Users: Use the same Gradle in IntelliJ -> Preferences -> Build, Execution, Deployment -> Build Tools -> Gradle use Gradle from "specified Location"
e.g. `~.sdkman/candidates/gradle/7.0.2`. Make sure *Gradle JVM* points to the JVM as the Project's JDK
====

== Install Postgres

* Install local Postgres DB. As of this writing we still recommend the older Postgres 12.x Version if you're
using the hosted https://www.elephantsql.com/[ElephantSQL] Service, as it will make it easier to exchange DB Dumps.
See https://medium.com/@viviennediegoencarnacion/getting-started-with-postgresql-on-mac-e6a5f48ee399[Getting started with Postgres on Mac] for a more detailed tutorial
+
----
$ brew install postgresql@12
postgresql@12 12.7 is already installed and up-to-date.
If you need to have postgresql@12 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/postgresql@12/bin:$PATH"' >> /Users/tillkuhn/.bash_profile
To have launchd start postgresql@12 now and restart at login:
  brew services start postgresql@12
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgresql@12 start
$ pg_ctl -D /usr/local/var/postgres  init
Success. You can now start the database server using:

pg_ctl -D /usr/local/var/postgres -l logfile start
$ psql postgres
psql (12.7)
Type "help" for help.

postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 yourname  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

CREATE ROLE angkor_dev WITH LOGIN PASSWORD 'angkor_dev';
ALTER ROLE angkor_dev CREATEDB;
CREATE DATABASE angkor_dev with owner angkor_dev;
\q
psql angkor_dev; -- must create extensions as root
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "hstore";

postgres=# \q
----

[CAUTION]
====
Above SQL snippets assume you're using default db settings as per `application.yml` default profile.
If you want to use different DB name or users, or use an existing remote DB, you use `config/application.properties` to
override without putting the custom settings to source control!
====

* Edit the `application.properties` in the `config/` folder (you can use the `*.tmpl` file in the same dir as a template)  to configure credentials for local external services such as *Postgres* and *Kafka*. Those will take precedence at runtime, but make sure you don't put this file under version control!
+
----
~/angkor/api$ cp config/application.properties.tmpl config/application.properties
~/angkor/api$ code config/application.properties
----

== Install other useful tools

----
$ brew install hadolint jq make
$ hadolint --version
Haskell Dockerfile Linter 2.4.1-no-git
$ jq --version
jq-1.6
$ gmake --version
GNU Make 4.3
----

== Anybody listening on port 8080?

[source,shell script]
----
$ gradle tasks

$ gradle bootRun
$ curl -sS http://localhost:8080/actuator/health
{"status":"UP"}
----

== Gradle Version Catalog

* https://blog.jdriven.com/2022/11/gradle-goodness-defining-plugin-versions-using-version-catalog/

== Metrics / Monitoring

* https://github.com/kirshiyin89/springboot-monitoring-demo/tree/feature/monitoring-with-custom-endpoints-and-security[How To Secure Custom Spring Boot Actuator Endpoints and Add Prometheus Metrics]
* https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/production-ready-metrics.html[Part V. Spring Boot Actuator: Production-ready features - Metrics / Micrometer]
* https://stackoverflow.com/questions/48451381/spring-boot-actuator-micrometer-metrics-disable-some[Spring Boot Actuator/Micrometer Metrics Disable Some]
* https://medium.com/javarevisited/unlocking-precision-metrics-in-spring-boot-with-micrometer-a-comprehensive-guide-6d72d6eaaf00[Unlocking Precision Metrics in Spring Boot with Micrometer: A Comprehensive Guide]
* https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.security[Spring Boot Actuator Endpoint Security]
* https://www.callicoder.com/spring-boot-actuator-metrics-monitoring-dashboard-prometheus-grafana/[Spring Boot Actuator metrics monitoring with Prometheus and Grafana]

.Example for filtered /actuator/metrics endpoint
----
# HELP jvm_memory_max_bytes The maximum amount of memory in bytes that can be used for memory management
# TYPE jvm_memory_max_bytes gauge
jvm_memory_max_bytes{app="angkor-api",area="nonheap",id="CodeCache",} 5.0331648E7
jvm_memory_max_bytes{app="angkor-api",area="nonheap",id="Metaspace",} -1.0
jvm_memory_max_bytes{app="angkor-api",area="nonheap",id="Compressed Class Space",} 1.073741824E9
jvm_memory_max_bytes{app="angkor-api",area="heap",id="G1 Eden Space",} -1.0
jvm_memory_max_bytes{app="angkor-api",area="heap",id="G1 Survivor Space",} -1.0
jvm_memory_max_bytes{app="angkor-api",area="heap",id="G1 Old Gen",} 8.589934592E9
# HELP process_cpu_usage The "recent cpu usage" for the Java Virtual Machine process
# TYPE process_cpu_usage gauge
process_cpu_usage{app="angkor-api",} 0.0
# HELP jdbc_connections_active Current number of active connections that have been allocated from the data source.
# TYPE jdbc_connections_active gauge
jdbc_connections_active{app="angkor-api",name="dataSource",} 0.0
# HELP process_start_time_seconds Start time of the process since unix epoch.
# TYPE process_start_time_seconds gauge
process_start_time_seconds{app="angkor-api",} 1.707417503734E9
----
