package org.timafe.p2b.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.vladmihalcea.hibernate.type.array.ListArrayType
import org.hibernate.annotations.Type
import org.hibernate.annotations.TypeDef
import org.timafe.p2b.Constants
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Id

@Entity
@TypeDef(
        name = "list-array",
        typeClass = com.vladmihalcea.hibernate.type.array.ListArrayType::class
        )
// @DynamoDBTable(tableName = Constants.DYNAMODB_PREFIX + "place")
data class Place(

        // @DynamoDBHashKey
        // @DynamoDBAutoGeneratedKey
        @Id
        var id: String?,

        // @DynamoDBAttribute
        var name: String,

        // @DynamoDBAttribute
        var summary: String?,

        @Type(type = "list-array")
        @Column(
        name = "coordinates",
        columnDefinition = "double precision[]"
        )
        var coordinates: List<Double> = listOf(1.2,3.4)
        //@DynamoDBAttribute
        //var updated: LocalDateTime = LocalDateTime.now()
)

