# https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI

#on: [push]
on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew build
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


