# https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: api-gradle-ci

#on: [push]
on:
  push:
    branches: #[ $default-branch ]
      - master
    #branches-ignore:
    #  - 'master'
    #  - 'release*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        working-directory: ./api
        run: |
          ./gradlew --no-daemon bootJar
          ls -l build/libs/app.jar
        env:
          CI: true
      # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


