# This is a basic workflow to help you get started with Actions

name: api-kotlin-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        # minimum: compileKotlin
        working-directory: ./api
        run: |
          ./gradlew --no-daemon bootJar
          ls -l build/libs/app.jar
        env:
          CI: true
