# https://github.com/hashicorp/setup-terraform
# https://www.terraform.io/docs/github-actions/setup-terraform.html
name: terraform-ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.3

    - name: Cache Terraform workdir
      uses: actions/cache@v2
      with:
        path: ./infra/.terraform
        key: ${{ runner.os }}-terraform-0.14.3
        restore-keys: ${{ runner.os }}-terraform-

    - name: Build with Terraform
      working-directory: ./infra
      run: |
        terraform version
        terraform init -backend=false
        terraform fmt -check
        terraform validate -no-color
