name: golang-ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # https://github.com/actions/cache/blob/main/examples.md#go---modules
      - name: Cache Go modules packages
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with Go
        working-directory: ./tools
        run: |
          make build

          # all tools are pushed to dockerhub, but we (still) need polly binary for systemd service
          aws s3 cp --no-progress dist/polly ${{ secrets.AWS_DEPLOY_TARGET }}/tools/polly

          # https://stackoverflow.com/questions/39371572/shorthand-syntax-for-message-attributes-in-the-send-message-command-in-aws-cli-f
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
          aws sns publish --topic-arn $TOPIC_ARN --message "{\"event\":\"s3push\",\"workflow\":\"$GITHUB_WORKFLOW\"}" \
              --message-attributes "GITHUB_SHA={DataType=String,StringValue=\"$GITHUB_SHA\"}, GITHUB_RUN_ID={DataType=String,StringValue=\"$GITHUB_RUN_ID\"}"
        env:
          CI: true
          TOPIC_ARN: ${{ secrets.TOPIC_ARN }}

      - name: Lint Dockerfile with hadolint
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: ./tools/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Password or personal access token used to log in to a Docker registry. If not set then no login will occur.

      # https://stackoverflow.com/a/58178121/4292075, https://stackoverflow.com/a/51761312/4292075
      - name: Set LATEST_REPO_TAG env
        run: echo "LATEST_REPO_TAG=$(git ls-remote --tags --sort='v:refname' | tail -n1 | sed 's/.*\///; s/\^{}//')" >> $GITHUB_ENV

      - name: Push to DockerHub
        uses: docker/build-push-action@v2 # https://github.com/docker/build-push-action
        with:
          context: ./tools
          file: ./tools/Dockerfile
          platforms: linux/arm64,linux/amd64 #linux/amd64,linux/386
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/angkor-tools:latest
          build-args: |
            LATEST_REPO_TAG=${{ env.LATEST_REPO_TAG }}
